---
openapi: 3.0.1
info:
  title: e-Commerce API
  description: Swagger UI
  version: 1.0.0
servers:
- url: http://localhost:8080
  description: Generated server url
tags:
- name: User API
  description: 유저 관리 (잔액 조회 및 충전)
- name: Product API
  description: 상품 관리 (조회, 상위 상품 조회)
- name: Payment API
  description: 결제 관련
- name: 쿠폰 API
  description: 쿠폰 관련 (쿠폰 목록, 발급)
- name: Order API
  description: 주문 관련
paths:
  "/user/charge":
    post:
      tags:
      - User API
      operationId: charge
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/UserChargeRequest"
        required: true
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/UserBalanceResponse"
  "/payment":
    post:
      tags:
      - Payment API
      operationId: payment
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/PaymentRequest"
        required: true
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/PaymentResponse"
  "/order":
    post:
      tags:
      - Order API
      operationId: order
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/OrderRequest"
        required: true
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/OrderResponse"
  "/coupon/issue":
    post:
      tags:
      - 쿠폰 API
      operationId: issueCoupon
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/CouponRequest"
        required: true
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/CouponResponse"
  "/user/balance/{userId}":
    get:
      tags:
      - User API
      operationId: getUserBalance
      parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/UserBalanceResponse"
  "/product/{productId}":
    get:
      tags:
      - Product API
      operationId: getProduct
      parameters:
      - name: productId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/ProductResponse"
  "/product/top":
    get:
      tags:
      - Product API
      operationId: getTopProductList
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/ProductResponse"
  "/coupon/list/{userId}":
    get:
      tags:
      - 쿠폰 API
      operationId: getCouponList
      parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/UserCouponResponse"
components:
  schemas:
    UserChargeRequest:
      type: object
      properties:
        userId:
          type: integer
          format: int64
        amount:
          type: integer
          format: int32
    UserBalanceResponse:
      type: object
      properties:
        userId:
          type: integer
          format: int64
        balance:
          type: integer
          format: int64
    PaymentRequest:
      type: object
      properties:
        orderId:
          type: integer
          format: int64
    PaymentResponse:
      type: object
      properties:
        paymentId:
          type: integer
          format: int64
        status:
          type: string
          enum:
          - COMPLETED
          - FAILED
    OrderRequest:
      type: object
      properties:
        userId:
          type: integer
          format: int64
        productId:
          type: integer
          format: int64
        couponId:
          type: integer
          format: int64
        quantity:
          type: integer
          format: int32
    OrderResponse:
      type: object
      properties:
        orderId:
          type: integer
          format: int64
        totalPrice:
          type: integer
          format: int64
        finalPrice:
          type: integer
          format: int64
    CouponRequest:
      type: object
      properties:
        userId:
          type: integer
          format: int64
        couponId:
          type: integer
          format: int64
    CouponResponse:
      type: object
      properties:
        couponId:
          type: integer
          format: int64
        name:
          type: string
        type:
          type: string
          enum:
          - PERCENT
          - PRICE
        value:
          type: integer
          format: int32
    ProductResponse:
      type: object
      properties:
        productId:
          type: integer
          format: int64
        name:
          type: string
        price:
          type: integer
          format: int32
        stock:
          type: integer
          format: int32
    UserCouponResponse:
      type: object
      properties:
        couponId:
          type: integer
          format: int64
        name:
          type: string
        type:
          type: string
          enum:
          - PERCENT
          - PRICE
        value:
          type: integer
          format: int32
        status:
          type: string
          enum:
          - AVAILABLE
          - USED
